//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Group()
        {
            this.GroupRegistrations = new HashSet<GroupRegistration>();
        }
    
        public int groupID { get; set; }
        public Nullable<System.DateTime> openingDate { get; set; }
        public Nullable<System.DateTime> destDate { get; set; }
        public string dayInTheWeek { get; set; }
        public Nullable<decimal> AmountWeekly { get; set; }
        public Nullable<decimal> AmountEnd { get; set; }
        public Nullable<int> IDGroupType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupRegistration> GroupRegistrations { get; set; }
        public virtual GroupType GroupType { get; set; }
    }
}
