//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupRegistration
    {
        public int GroupRegistrationID { get; set; }
        public string Status_user { get; set; }
        public Nullable<int> IDgroup { get; set; }
        public Nullable<int> IDuser { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual User User { get; set; }
    }
}
