//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.GroupRegistrations = new HashSet<GroupRegistration>();
            this.weightings = new HashSet<weighting>();
        }
    
        public int userID { get; set; }
        public Nullable<double> height { get; set; }
        public string userName { get; set; }
        public Nullable<System.DateTime> DateOfRegistration { get; set; }
        public string tz { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string gende { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupRegistration> GroupRegistrations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<weighting> weightings { get; set; }
    }
}
